import '../models/customer.dart';
import '../models/customer_summary.dart';

class CustomerMockService {
  Future<List<Customer>> getCustomers() async {
    await Future<void>.delayed(const Duration(milliseconds: 450));

    return [
      Customer(
        id: 'CUS-101',
        customerCode: 'CUS-0001',
        name: 'Ahmed Trading',
        type: CustomerType.business,
        phone: '01012345678',
        mobile: '01012345678',
        email: 'sales@ahmedtrading.com',
        website: 'www.ahmedtrading.com',
        country: 'Egypt',
        state: 'Cairo',
        city: 'Cairo',
        address: 'Nasr City, Cairo',
        postalCode: '11371',
        openingBalance: 12000,
        balance: 25000,
        creditLimit: 150000,
        paymentTerms: 'Net 30',
        status: CustomerStatus.active,
        notes: 'Priority customer for bulk orders.',
        createdAt: DateTime(2024, 1, 18),
        updatedAt: DateTime(2025, 7, 10),
      ),
      Customer(
        id: 'CUS-102',
        customerCode: 'CUS-0002',
        name: 'Nahla Al-Masry',
        type: CustomerType.individual,
        phone: '01199887766',
        mobile: '01199887766',
        email: 'nahla@gmail.com',
        website: null,
        country: 'Egypt',
        state: 'Alexandria',
        city: 'Alexandria',
        address: 'Smouha, Alexandria',
        postalCode: '21500',
        openingBalance: 5000,
        balance: 0,
        creditLimit: 40000,
        paymentTerms: 'Cash',
        status: CustomerStatus.active,
        notes: 'Retail purchase customer.',
        createdAt: DateTime(2024, 3, 16),
        updatedAt: DateTime(2025, 6, 23),
      ),
      Customer(
        id: 'CUS-103',
        customerCode: 'CUS-0003',
        name: 'Blue Ocean Retail',
        type: CustomerType.business,
        phone: '01222445566',
        mobile: '01222445566',
        email: 'accounts@blueoceanretail.com',
        website: 'www.blueoceanretail.com',
        country: 'Egypt',
        state: 'Giza',
        city: 'Dokki',
        address: 'Dokki, Giza',
        postalCode: '12611',
        openingBalance: 18000,
        balance: 42000,
        creditLimit: 200000,
        paymentTerms: 'Net 45',
        status: CustomerStatus.inactive,
        notes: 'Currently on hold for seasonal review.',
        createdAt: DateTime(2023, 11, 5),
        updatedAt: DateTime(2025, 4, 2),
      ),
      Customer(
        id: 'CUS-104',
        customerCode: 'CUS-0004',
        name: 'Omar Hassan',
        type: CustomerType.individual,
        phone: '01551445577',
        mobile: '01551445577',
        email: 'omar.hassan@icloud.com',
        website: null,
        country: 'Egypt',
        state: 'Mansoura',
        city: 'Mansoura',
        address: 'Mansoura City',
        postalCode: '35511',
        openingBalance: 3000,
        balance: 1800,
        creditLimit: 25000,
        paymentTerms: 'Net 15',
        status: CustomerStatus.active,
        notes: 'Excellent payment history.',
        createdAt: DateTime(2024, 8, 7),
        updatedAt: DateTime(2025, 7, 1),
      ),
      Customer(
        id: 'CUS-105',
        customerCode: 'CUS-0005',
        name: 'Atlas Supplies',
        type: CustomerType.business,
        phone: '01098765432',
        mobile: '01098765432',
        email: 'ops@atlassupplies.com',
        website: 'www.atlassupplies.com',
        country: 'Saudi Arabia',
        state: 'Riyadh',
        city: 'Riyadh',
        address: 'King Fahd Road, Riyadh',
        postalCode: '11564',
        openingBalance: 35000,
        balance: 86000,
        creditLimit: 330000,
        paymentTerms: 'Net 60',
        status: CustomerStatus.suspended,
        notes: 'Requires credit review.',
        createdAt: DateTime(2023, 5, 20),
        updatedAt: DateTime(2025, 2, 14),
      ),
      Customer(
        id: 'CUS-106',
        customerCode: 'CUS-0006',
        name: 'Modern Office Co.',
        type: CustomerType.business,
        phone: '01234567890',
        mobile: '01234567890',
        email: 'admin@modernoffice.com',
        website: 'www.modernoffice.com',
        country: 'Egypt',
        state: 'Cairo',
        city: 'Heliopolis',
        address: 'Heliopolis, Cairo',
        postalCode: '11742',
        openingBalance: 22000,
        balance: 31000,
        creditLimit: 180000,
        paymentTerms: 'Net 30',
        status: CustomerStatus.active,
        notes: 'Corporate client with recurring monthly billing.',
        createdAt: DateTime(2022, 12, 15),
        updatedAt: DateTime(2025, 5, 30),
      ),
    ];
  }

  Future<CustomerSummary> getCustomerSummary() async {
    final customers = await getCustomers();
    final activeCustomers = customers.where((customer) => customer.status == CustomerStatus.active).length;
    final inactiveCustomers = customers.where((customer) => customer.status == CustomerStatus.inactive).length;
    final outstandingBalance = customers
        .where((customer) => customer.balance > 0)
        .fold<double>(0, (sum, customer) => sum + customer.balance);

    return CustomerSummary(
      totalCustomers: customers.length,
      activeCustomers: activeCustomers,
      inactiveCustomers: inactiveCustomers,
      outstandingBalance: outstandingBalance,
    );
  }
}
